export const ListBooks = [
  {
    id: 'story01',
    story: 'El Gato con Botas',
    author: 'Miguel de Cervantes',
    textColor: '#ffffff',
    background: '#fa6400',
    srcImg: require('../../assets/images/story01/img01.webp'),
  },
  {
    id: 'story02',
    story: 'Los 3 Cerditos',
    author: 'Tu Mama',
    textColor: '#ffffff',
    background: '#ea4c89',
    srcImg: require('../../assets/images/story02/image01.webp'),
  },
  {
    id: 'story03',
    story: 'La Liebre y la Tortuga',
    author: 'anonimo',
    textColor: '#ffffff',
    background: '#405cf5',
    srcImg: require('../../assets/images/story03/image01.webp'),
  },
  {
    id: 'story04',
    story: 'Los Musicos de Bremen',
    author: 'Juan Perez',
    textColor: '#ffffff',
    background: '#303446',
    srcImg: require('../../assets/images/story04/image01.webp'),
  },
  {
    id: 'story05',
    story: 'El Árbol Mágico',
    author: 'Maria Rodriguez',
    textColor: '#ffffff',
    background: '#990000',
    srcImg: require('../../assets/images/story05/image01.webp'),
  },
  {
    id: 'story06',
    story: 'Pedro y el Lobo',
    author: 'Carlos Gutierrez',
    textColor: '#ffffff',
    background: 'purple',
    srcImg: require('../../assets/images/story06/image01.webp'),
  },
  {
    id: 'story07',
    story: 'El Patito Feo',
    author: 'Ana Martinez',
    textColor: '#ffffff',
    background: '#09d',
    srcImg: require('../../assets/images/story07/image01.webp'),
  },
  {
    id: 'story08',
    story: 'El Lobo y los 7 Cabritos',
    author: 'Sofia Ramirez',
    textColor: '#181818',
    background: '#FFd000',
    srcImg: require('../../assets/images/story08/image01.webp'),
  },
  {
    id: 'story09',
    story: 'Cuentos cortos 1',
    author: 'Luis Fernandez',
    textColor: '#181818',
    background: '#28BAA7',
    srcImg: require('../../assets/images/story09/image01.png'),
  },
]
